# Chapter 17

## Support vector machines

### 17.1 Training a linear classifier

In [ ]:
from sklearn.svm import LinearSVC
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
import numpy as np

In [ ]:
iris = datasets.load_iris()
features = iris.data[:100,:2]
target = iris.target[:100]

In [ ]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

svc = LinearSVC(C=1.0)
model = svc.fit(features_standardized, target)

In [ ]:
from matplotlib import pyplot as plt

plt.figure(figsize=(40,20))

color = ["black" if c == 0 else "lightgrey" for c in target] 
plt.scatter(features_standardized[:,0], features_standardized[:,1], c=color)

w = svc.coef_[0]
a=-w[0]/w[1]
xx = np.linspace(-2.5, 2.5)
yy = a * xx - (svc.intercept_[0]) / w[1]

plt.plot(xx, yy)
plt.axis("off"), plt.show();

In [ ]:
new = [[-2,3]]
svc.predict(new)

## 17.2 Handling linearly inseparable classes using kernels

In [ ]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
import numpy as np

In [ ]:
np.random.seed(0)

features = np.random.randn(200, 2)
target_xor = np.logical_xor(features[:, 0] > 0, features[:, 1] > 0) 
target = np.where(target_xor, 0, 1)

svc = SVC(kernel="rbf", random_state=0, gamma=1, C=1) 
model = svc.fit(features, target)

In [ ]:
from matplotlib.colors import ListedColormap 
import matplotlib.pyplot as plt

In [ ]:
def plot_decision_regions(X, y, classifier):
    cmap = ListedColormap(("red", "blue"))
    xx1, xx2 = np.meshgrid(np.arange(-3, 3, 0.02), np.arange(-3, 3, 0.02)) 
    Z = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    Z = Z.reshape(xx1.shape)
    plt.contourf(xx1, xx2, Z, alpha=0.1, cmap=cmap)
    
    for idx, cl in enumerate(np.unique(y)): 
        plt.scatter(x=X[y == cl, 0], y=X[y == cl, 1],
            alpha=0.8, c=cmap(idx),
            marker="+", label=cl)

svc_linear = SVC(kernel="linear", random_state=0, C=1)
svc_linear.fit(features, target)

plt.figure(figsize=(40,20))
plot_decision_regions(features, target, classifier=svc_linear)
plt.axis("off"), plt.show();

In [ ]:
svc = SVC(kernel="rbf", random_state=0, gamma=2, C=1) 
model = svc.fit(features, target)

In [ ]:
plt.figure(figsize=(40,20))
plot_decision_regions(features, target, classifier=svc)
plt.axis("off"), plt.show();

### 17.3 Creating predicted probabilities

In [41]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
import numpy as np

In [42]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [43]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

svc = SVC(kernel="linear", probability=True, random_state=0) 
model = svc.fit(features_standardized, target)

new_observation = [[.4, .4, .4, .4]]
model.predict_proba(new_observation)

array([[0.00541761, 0.97348825, 0.02109414]])

### 17.4 Identifying support vectors

In [44]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
import numpy as np

In [45]:

iris = datasets.load_iris()
features = iris.data[:100,:]
target = iris.target[:100]

In [47]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

svc = SVC(kernel="linear", random_state=0) 
model = svc.fit(features_standardized, target)

In [51]:
print(
    f'Support vectors: {model.support_vectors_}',
    f'Indices of support vectors: {model.support_}',
    f'Number of support vectors: {model.n_support_}',
    sep = '\n'
)

Support vectors: [[-0.5810659   0.42196824 -0.80497402 -0.50860702]
 [-1.52079513 -1.67737625 -1.08231219 -0.86427627]
 [-0.89430898 -1.4674418   0.30437864  0.38056609]
 [-0.5810659  -1.25750735  0.09637501  0.55840072]]
Indices of support vectors: [23 41 57 98]
Number of support vectors: [2 2]


### 17.5 Handling imbalanced classes

In [52]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
import numpy as np

In [53]:
iris = datasets.load_iris()
features = iris.data[:100,:]
target = iris.target[:100]

In [54]:
features = features[40:,:]
target = target[40:]
target = np.where((target == 0), 0, 1)

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

svc = SVC(kernel="linear", class_weight="balanced", C=1.0, random_state=0)
model = svc.fit(features_standardized, target)